name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  postgres: ^3.0.0
  pdf: ^3.10.0
  bcrypt: ^1.1.3
  path: ^1.8.0
  docx_template: ^0.4.0
  http: ^1.1.0

flutter:
  assets:
    - ../../assets/files/Good Moral.pdf

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
