name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  postgres: ^3.0.0
  pdf: ^3.10.0
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
